### ISSUE TITLE
.NET Standard support

### ISSUE THREAD

**Issue by jbogard** [jbevain/mono.reflection#15]
In case someone comes here looking to see if this library can support .NET Standard and .NET Core, I've attached the compatibility report from apiport.exe. No support possible until .NET Standard 2.0 it seems.

[ApiPortAnalysis.xlsx](https://github.com/jbevain/mono.reflection/files/551838/ApiPortAnalysis.xlsx)

@hazzik in case you look at this for DelegateDecompiler

**Comment by jbevain** [comment]
Thanks @jbogard! (What are you using this for?)

**Comment by hazzik** [comment]
@jbevain there is a high demand in support of EntityFrameworkCore by DelegateDecompiler, which depends on Mono.Reflection to get the IL AST

**Comment by jbevain** [comment]
@hazzik that's awesome. I started something like that ages ago but never got to finishing it. Glad you did!

**Comment by jbevain** [comment]
@hazzik we should definitely integrate that into http://github.com/jbevain/mono.linq.expressions/ somewhoe!

**Comment by jbevain** [comment]
Added support for .NET Standard 2.0. Thanks!
