### ISSUE TITLE
DLL produced causes LoaderException during AssemblyLoad in vNext

### ISSUE THREAD

**Issue by chuckbeasley** [jbevain/mono.reflection#9]
I load an assembly as follows:
AssemblyDefinition asm2 = MetadataMapper.MapAssembly(AppDomain.CurrentDomain.GetAssemblies().Where(x => x.FullName == "Ats.OpenOne.Web.Controllers, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null").First());

That part works fine. Next, I write the DLL out to a file, as follows:
asm2.Write(@"C:\Source\Workspace\Ats.OpenOne\artifacts\bin\" + projectNames[10] + @"\Debug\dnx451\" + projectNames[10] + "_.dll");

When I attempt to load the assembly into memory, I get a LoaderException upon hitting this code:
Assembly onDiskAssembly2 = Assembly.LoadFile(@"C:\Source\Workspace\Ats.OpenOne\artifacts\bin\" + projectNames[10] + @"\Debug\dnx451\" + projectNames[10] + "_.dll");

I've researched into this and the main difference I see is MetadataSystem is null, but is populated when I load a DLL written by Mono Cecil from disk.

**Comment by jbevain** [comment]
@chuckbeasley hey Chuck, can you upload the assembly somewhere? Thanks!

**Comment by chuckbeasley** [comment]
@jbevain Hey JB. Check your inbox.

**Comment by jbevain** [comment]
@chuckbeasley got it thanks, it might be a while before I get to it.

**Comment by chuckbeasley** [comment]
@jbevain cool! anyplace you recommend I start looking?

**Comment by jbevain** [comment]
Should be fixed in 15ba007af7d639821784b7b6c3648836ef197165
